#import "AppDelegate.h"

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>

#import <TSBackgroundFetch/TSBackgroundFetch.h>

#if RCT_DEV
#import <React/RCTDevLoadingView.h>
#endif

// This is the header file automagically generated by XCode when Swift code marked @objc is incorporated.
// SWIFT_MODULE_NAME is based on PRODUCT_MODULE_NAME in XCode which varies by target.
// IS_PATHIFY_TEST_TARGET is defined in the PathifyTest XCode scheme.

#if IS_PATHIFY_TEST_TARGET
#import "PathifyTest-Swift.h"
#else
#import "Pathify-Swift.h"
#endif

#ifdef FB_SONARKIT_ENABLED
#import <FlipperKit/FlipperClient.h>
#import <FlipperKitLayoutPlugin/FlipperKitLayoutPlugin.h>
#import <FlipperKitUserDefaultsPlugin/FKUserDefaultsPlugin.h>
#import <FlipperKitNetworkPlugin/FlipperKitNetworkPlugin.h>
#import <SKIOSNetworkPlugin/SKIOSNetworkAdapter.h>
#import <FlipperKitReactPlugin/FlipperKitReactPlugin.h>

static void InitializeFlipper(UIApplication *application) {
  FlipperClient *client = [FlipperClient sharedClient];
  SKDescriptorMapper *layoutDescriptorMapper = [[SKDescriptorMapper alloc] initWithDefaults];
  [client addPlugin:[[FlipperKitLayoutPlugin alloc] initWithRootNode:application withDescriptorMapper:layoutDescriptorMapper]];
  [client addPlugin:[[FKUserDefaultsPlugin alloc] initWithSuiteName:nil]];
  [client addPlugin:[FlipperKitReactPlugin new]];
  [client addPlugin:[[FlipperKitNetworkPlugin alloc] initWithNetworkAdapter:[SKIOSNetworkAdapter new]]];
  [client start];
}
#endif

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
#ifdef FB_SONARKIT_ENABLED
  InitializeFlipper(application);
#endif

  NSURL *jsCodeLocation;

// https://facebook.github.io/react-native/docs/running-on-device
#ifdef DEBUG
  jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
  
  // TODO warning: bridge currently unused
  RCTBridge *bridge = [[RCTBridge alloc] initWithBundleURL:jsCodeLocation
    moduleProvider:nil
    launchOptions:launchOptions];

#if RCT_DEV
[bridge moduleForClass:[RCTDevLoadingView class]];
#endif

  NSMutableDictionary *initialPropertiesDictionary = [NSMutableDictionary dictionary];

  // Custom code for Pathify: retrieve the environment variables for the running app and pass them to the RCTRootView.
  // Note envrironment variables defined in the XCode scheme are unfortunately only passed when run from XCode directly,
  // not when app is launched via the icon.
  NSDictionary *environment = [[NSProcessInfo processInfo] environment];
  [initialPropertiesDictionary addEntriesFromDictionary:environment];

  // Add XCode version and buildNumber to initialPropertiesDictionary.
  NSString *version = [[[NSBundle mainBundle] infoDictionary] objectForKey: @"CFBundleShortVersionString"];
  [initialPropertiesDictionary setValue:version forKey:@"appVersion"];

  NSString *buildNumber = [[[NSBundle mainBundle] infoDictionary] objectForKey: @"CFBundleVersion"];
  [initialPropertiesDictionary setValue:buildNumber forKey:@"appBuild"];

  // Example of how to do Swift function call with no parameters from Objective-C and pass the result to the app:
  [initialPropertiesDictionary setValue:[PathifyNative foo] forKey:@"foo"];

  // Objective-C to Swift with a parameter:
  // The function in Swift is just loadSampleData(props), simple as can be, but you have to call it this cryptic way,
  // which you wouldn't even know without digging in the synthesized header file where you find loadSampleDataWithProps:
  [PathifyNative loadSampleDataWithProps:initialPropertiesDictionary];
 
  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"Pathify" // Corresponds to name in app.json
                                               initialProperties:initialPropertiesDictionary
                                                   launchOptions:launchOptions];

  // rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:0.0f blue:0.0f alpha:1];
  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];

  // Pro Tip
  // As your App Bundle grows in size, you may start to see a white screen flash between your splash screen and the
  // display of your root application view. If this is the case, you can add the following code to AppDelegate.m
  // in order to keep your splash screen displayed during the transition.
  UIView* launchScreenView = [[[NSBundle mainBundle] loadNibNamed:@"LaunchScreen" owner:self options:nil] objectAtIndex:0];
  launchScreenView.frame = self.window.bounds;
  rootView.loadingView = launchScreenView;

  // [REQUIRED] Register BackgroundFetch
  [[TSBackgroundFetch sharedInstance] didFinishLaunching];

  return YES;
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

@end
