require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# Uncomment the next line to define a global platform for your project
platform :ios, '14.4'

# ignore all warnings from all pods
inhibit_all_warnings!

ENV['REACT_NATIVE_MAPBOX_MAPBOX_IOS_VERSION'] = '~> 6.2.1';
ENV['$ReactNativeMapboxGLIOSVersion'] = '~> 6.2.1';

def setupPathifyPods

  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  # use_frameworks! :linkage => :static
  # use_modular_headers!

  # from https://stackoverflow.com/questions/13208202/ignore-xcode-warnings-when-using-cocoapods/13209057#13209057
  # how to ignore warnings from a specific pod
  # pod 'FBSDKCoreKit', :inhibit_warnings => true

  require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!

  #   installer.pods_project.targets.each do |target|
  #     # workaround per https://github.com/facebook/react-native/issues/24192
  #     if target.name == "React"
  #       target.remove_from_project
  #     end

  #     # workaround per https://github.com/facebook/react-native/issues/20492
  #     # The following is needed to ensure the "archive" step works in XCode.
  #     # It removes React & Yoga from the Pods project, as it is already included in the main project.
  #     # Without this, you'd see errors when you archive like:
  #     # "Multiple commands produce ... libReact.a"
  #     # "Multiple commands produce ... libyoga.a"

  #     targets_to_ignore = %w(React yoga)
  #     if targets_to_ignore.include? target.name
  #       target.remove_from_project
  #     end
  #   end
end


target 'PathifyUITests' do
  inherit! :search_paths
  # Pods for testing
end

target 'Pathify' do
  setupPathifyPods
end

target 'PathifyTest' do
  setupPathifyPods
end

post_install do |installer|
  # flipper_post_install(installer)
  installer.generated_projects.each do |project|
    project.build_configurations.each do |config|
        if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 14.4
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.4'
        end
    end
    project.targets.each do |target|
      target.build_configurations.each do |config|
        if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 14.4
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.4'
        end
      end
    end
  end
end
