$RNMapboxMapsImpl = 'mapbox'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# Uncomment the next line to define a global platform for your project
platform :ios, '14.1'

install! 'cocoapods', :deterministic_uuids => false

def setupPathifyPods

  production = ENV["PRODUCTION"] == "1"

  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  # use_frameworks! :linkage => :static
  # use_modular_headers!

  require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    :production => production,
    :hermes_enabled => false,
    :fabric_enabled => flags[:fabric_enabled],
    # :flipper_configuration => FlipperConfiguration.enabled,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
end

target 'PathifyUITests' do
  inherit! :search_paths
  # Pods for testing
end

target 'Pathify' do
  setupPathifyPods
end

target 'PathifyTest' do
  setupPathifyPods
end

pre_install do |installer|
  $RNMapboxMaps.pre_install(installer)
end

post_install do |installer|
  # flipper_post_install(installer)
  installer.generated_projects.each do |project|
    project.build_configurations.each do |config|
        if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 14.1
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.1'
        end
    end
    project.targets.each do |target|
      target.build_configurations.each do |config|
        if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 14.1
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.1'
        end
      end
    end
  end
  react_native_post_install(installer)
  `sed -i -e  $'s/__IPHONE_12_0/__IPHONE_15_0/' Pods/RCT-Folly/folly/portability/Time.h`
end
